name: meta-maas
version: 0.1
summary: Tool to manage multiple MAAS regions
description: Tool to manage multiple MAAS regions
grade: stable
confinement: strict

apps:
  meta-maas:
    command: bin/meta-maas
    plugs:
      - home
      - network-bind

parts:
  meta-maas:
    plugin: python
    source: .
    requirements: requirements.txt
  meta-html-build:
    plugin: gulp
    source: .
    gulp-tasks:
      - default
  meta-html-install:
    plugin: dump
    source: parts/meta-html-build/build/meta_maas/html
    after:
      - meta-html-build
    organize:
      assets: lib/python3.5/site-packages/meta_maas/html/assets
      libs: lib/python3.5/site-packages/meta_maas/html/libs
