name: meta-maas
version: 0.1
summary: Tool to manage multiple MAAS regions
description: Tool to manage multiple MAAS regions
grade: stable
confinement: strict

apps:
  meta-maas:
    command: bin/meta-maas
    plugs:
      - home
      - network-bind

parts:
  meta-maas:
    plugin: python
    source: .
    requirements: requirements.txt
